language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: ardamax-github
    token:
      secure: a7954637d60572461970f63d049115f321b95d20
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'